apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mateo-ai-frontend-ingress
  namespace: $NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: aichat.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mateo-ai-frontend
            port:
              number: 80
